---
title: "Plan_DT"
format: html
editor: visual
author: |
  [Olivier Meslin](https://github.com/oliviermeslin)
  [Mélina Hillion](https://github.com/melinahillion)
---

Restriction du champ: méthodes ensemblistes à base d'arbres.

# Théorie

## Pourquoi utiliser des méthodes ensemblistes?

Avantages/inconvénients

## Comment fonctionnent les méthodes ensemblistes?

- Présentation intuitive et peu matheuse

### Qu'est-ce qu'un arbre?

### Qu'est-ce qu'une forêt aléatoire?

- Présentation;
- Limites à l'overfitting.

### Qu'est-ce qu'un algorithme de boosting?

- Présentation;
- Pas de limite à l'overfitting.

### Différence entre RF et GBRT

## Détail mathématique

### Qu'est-ce qu'un arbre?

### Comment on construit un arbre?

## Rôle et interprétation des principaux hyperparamètres

gamma, beta, alpha, lambda, eta, M, T, nb de quantiles;
method = "hist"

# Cas d'usage

- Données (pouvant être rendues) publiques
- Notebooks déployables sur le datalab
- Code en Python

## Régression

### Cas général

### Régression en présence d'outliers

=> Changement de fonction de perte

## Classification

### Cas général

### Classification déséquilibrée

=> Pondération de la classe minoritaire






